inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  Exclude:
    - 'tasks/release/**/*'

Gemspec/RequireMFA:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'lib/aws-activejob-sqs.rb'
    - 'spec/aws-activejob-sqs_spec.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/aws/active_job/sqs/configuration.rb'
